
logging:
  level:
      org:
        springframework: INFO

spring:

  mvc:
    view:
      prefix: /views/
      suffix: .html

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # h2-console
  h2:
    console:
      enabled: true

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
